# -*- coding: utf-8 -*-
"""
Name data for 124 countries/cultures.
Each entry: {'surnames': [...], 'male': [...], 'female': [...]}
Name order convention stored in EASTERN_ORDER set (surname first).
"""

EASTERN_ORDER = {
    'chinese', 'japanese', 'korean', 'vietnamese', 'hungarian',
    'cambodian', 'mongolian', 'burmese', 'lao', 'thai',
}

NAME_DATA = {
    # ── East Asia ──
    'chinese': {
        'surnames': ['Zhao','Qian','Sun','Li','Zhou','Wu','Zheng','Wang','Chen','Yang','Liu','Huang','Lin','Zhang','He'],
        'male': ['Long','Wei','Jun','Ming','Hao','Yi','Xiang','Feng','Tao','Jie','Lei','Bo','Cheng','Peng','Kai'],
        'female': ['Yan','Mei','Xue','Ling','Yue','Qing','Lan','Zhi','Rui','Jing','Xin','Ying','Na','Fang','Dan']},
    'japanese': {
        'surnames': ['Sato','Suzuki','Takahashi','Tanaka','Watanabe','Ito','Yamamoto','Nakamura','Kobayashi','Kato'],
        'male': ['Haruto','Yuto','Sota','Riku','Haruki','Hinata','Kaito','Sora','Ren','Minato'],
        'female': ['Hina','Yui','Mio','Ichika','Rin','Sakura','Akari','Yuna','Himari','Koharu']},
    'korean': {
        'surnames': ['Kim','Lee','Park','Choi','Jung','Kang','Cho','Yoon','Jang','Lim'],
        'male': ['Minho','Joon','Sungho','Hyun','Doyun','Jiwon','Taeyang','Seojun','Hajun','Siwoo'],
        'female': ['Jiyeon','Soyeon','Minji','Yuna','Haeun','Serin','Dahyun','Chaeyoung','Soojin','Eunbi']},
    'taiwanese': {
        'surnames': ['Chen','Lin','Huang','Zhang','Li','Wang','Wu','Liu','Cai','Yang'],
        'male': ['Junhao','Yichen','Zhehan','Weijie','Jiahao','Mingxuan','Yuxuan','Zhiyuan'],
        'female': ['Yuxin','Xinyi','Yahan','Yuting','Jiaxin','Shihan','Yuxuan','Ziyu']},
    'mongolian': {
        'surnames': ['Borjigin','Bat','Bold','Ganbat','Nergui','Sukhbaatar','Tserendorj','Erdene'],
        'male': ['Batbayar','Ganbaatar','Temujin','Munkh','Baatar','Erden','Chinggis','Sukh'],
        'female': ['Oyunbileg','Sarnai','Tsetseg','Enkhtuya','Bayarmaa','Altantsetseg','Solongo','Narantuya']},

    # ── Southeast Asia ──
    'vietnamese': {
        'surnames': ['Nguyen','Tran','Le','Pham','Hoang','Vo','Dang','Bui','Do','Ho'],
        'male': ['Minh','Duc','Hieu','Tuan','Thanh','Hoang','Quang','Trung','Dung','Hung'],
        'female': ['Linh','Trang','Huong','Thao','Ngoc','Mai','Lan','Anh','Hanh','Phuong']},
    'thai': {
        'surnames': ['Saetang','Srisuk','Jaidee','Thongkham','Boonmee','Rattana','Suwanna','Phanit'],
        'male': ['Somchai','Arthit','Nattapong','Wichit','Kittisak','Prem','Tanawat','Chatchai'],
        'female': ['Siriporn','Nattaya','Ploy','Kannika','Siriwan','Lalita','Nisa','Araya']},
    'filipino': {
        'surnames': ['Santos','Reyes','Cruz','Garcia','Ramos','Mendoza','Torres','Flores','Villanueva','Gonzales'],
        'male': ['Juan','Jose','Miguel','Rafael','Marco','Carlos','Gabriel','Antonio'],
        'female': ['Maria','Ana','Rosa','Carmen','Isabella','Sofia','Lucia','Elena']},
    'indonesian': {
        'surnames': ['Wijaya','Susanto','Hartono','Setiawan','Kurniawan','Santoso','Gunawan','Wibowo'],
        'male': ['Budi','Agus','Eko','Hadi','Rizky','Dimas','Fajar','Arif'],
        'female': ['Siti','Dewi','Putri','Ayu','Rani','Indah','Wulan','Sari']},
    'malaysian': {
        'surnames': ['Tan','Lim','Lee','Wong','Ng','Abdullah','Ahmad','Hassan'],
        'male': ['Amir','Faisal','Hafiz','Irfan','Rizwan','Azlan','Danish','Harith'],
        'female': ['Nurul','Aisyah','Farah','Hana','Nadia','Siti','Amira','Zara']},
    'singaporean': {
        'surnames': ['Tan','Lim','Lee','Ong','Wong','Goh','Chua','Chan','Koh','Teo'],
        'male': ['Wei Jie','Jun Wei','Zhi Hao','Yi Xuan','Jia Jun','Kai Wen','Rui En','Hao Yu'],
        'female': ['Xin Yi','Jia Xin','Yu Xuan','Jia Ying','Xin Hui','Kai Lin','Wen Xin','Shi Min']},
    'burmese': {
        'surnames': ['U','Daw','Ko','Ma','Maung','Naw','Saw','Nan'],
        'male': ['Aung','Kyaw','Zaw','Myo','Thet','Htet','Naing','Thura'],
        'female': ['Aye','Khin','Mya','Nwe','Phyu','Su','Thin','Yin']},
    'cambodian': {
        'surnames': ['Sok','Chan','Chea','Hem','Heng','Keo','Ly','Mao','Phan','Sar'],
        'male': ['Dara','Piseth','Sophal','Chanthol','Virak','Sambath','Sokha','Phearith'],
        'female': ['Sreymom','Channary','Bopha','Malis','Rachana','Sophea','Theary','Vanna']},
    'lao': {
        'surnames': ['Souphanouvong','Phomvihane','Inthavong','Keomanivong','Chanthavong'],
        'male': ['Khamla','Bounmy','Somphou','Viengkham','Thongchanh','Anousone','Bounsou','Keovilay'],
        'female': ['Chansouk','Manichanh','Douangchanh','Vilayphone','Phimmasone','Bouachanh','Ketsana','Noy']},

    # ── South Asia ──
    'indian': {
        'surnames': ['Sharma','Verma','Gupta','Singh','Kumar','Patel','Reddy','Joshi','Nair','Iyer'],
        'male': ['Arjun','Vihaan','Aditya','Sai','Reyansh','Ayaan','Krishna','Ishaan','Rohan','Dev'],
        'female': ['Aanya','Saanvi','Prisha','Diya','Ananya','Aadhya','Isha','Myra','Kavya','Riya']},
    'pakistani': {
        'surnames': ['Khan','Malik','Ahmed','Ali','Hussain','Shah','Butt','Chaudhry','Iqbal','Siddiqui'],
        'male': ['Muhammad','Ali','Ahmed','Hassan','Bilal','Usman','Hamza','Zain','Omar','Faisal'],
        'female': ['Fatima','Ayesha','Zainab','Maryam','Sana','Hira','Noor','Amina','Rabia','Mehreen']},
    'bangladeshi': {
        'surnames': ['Rahman','Hossain','Islam','Ahmed','Alam','Uddin','Begum','Chowdhury'],
        'male': ['Rahim','Farhan','Tanvir','Sabbir','Nabil','Mahfuz','Shahriar','Arif'],
        'female': ['Tasnim','Fariha','Nusrat','Lamia','Sumaiya','Jannatul','Mim','Tania']},
    'sri_lankan': {
        'surnames': ['Fernando','Perera','De Silva','Jayawardena','Bandara','Wijesinghe','Rathnayake','Gunasekara'],
        'male': ['Kasun','Chaminda','Dilshan','Nuwan','Lahiru','Thisara','Dinesh','Isuru'],
        'female': ['Sachini','Nadeesha','Dilini','Tharushi','Kavindi','Nimali','Hashini','Sewwandi']},
    'nepali': {
        'surnames': ['Sharma','Thapa','Gurung','Tamang','Shrestha','Rai','Magar','Lama'],
        'male': ['Bijay','Santosh','Dipesh','Sujan','Roshan','Aashish','Sagar','Manish'],
        'female': ['Sunita','Sushila','Anita','Sabina','Puja','Muna','Srijana','Roshni']},
    'bhutanese': {
        'surnames': ['Dorji','Wangchuk','Tshering','Namgay','Tobgay','Penjor','Rinzin','Yeshey'],
        'male': ['Tenzin','Karma','Sonam','Pema','Jigme','Ugyen','Kinley','Tandin'],
        'female': ['Dechen','Choden','Yangzom','Deki','Tshomo','Sangay','Lhamo','Rinchen']},
    'maldivian': {
        'surnames': ['Ibrahim','Ahmed','Mohamed','Ali','Hassan','Hussain','Ismail','Adam'],
        'male': ['Ahmed','Ibrahim','Mohamed','Yoosuf','Ali','Hussain','Ismail','Hassan'],
        'female': ['Aishath','Mariyam','Fathimath','Aminath','Hawwa','Khadija','Safiya','Halima']},

    # ── Central Asia ──
    'kazakh': {
        'surnames': ['Nursultan','Tokayev','Nazarbayev','Kunaev','Satpayev','Abai','Auezov','Suleimenov'],
        'male': ['Nurlan','Yerlan','Askar','Dauren','Baurzhan','Serik','Marat','Kairat'],
        'female': ['Ainur','Gulnara','Zhanna','Saule','Madina','Asel','Dinara','Karlygash']},
    'uzbek': {
        'surnames': ['Karimov','Mirziyoyev','Rashidov','Alimov','Usmanov','Khamidov','Rakhimov','Sultanov'],
        'male': ['Timur','Bobur','Sardor','Jasur','Dilshod','Sherzod','Rustam','Bakhtiyor'],
        'female': ['Dilnoza','Gulnora','Nodira','Feruza','Malika','Shahlo','Lola','Sevara']},
    'kyrgyz': {
        'surnames': ['Atambayev','Bakiyev','Akaev','Jeenbekov','Toktogulov','Sadyr','Osmonov','Aitmatov'],
        'male': ['Aibek','Chyngyz','Nursultan','Bektur','Azamat','Manas','Eldar','Taalai'],
        'female': ['Aizhan','Begaiym','Cholpon','Elzada','Kanykei','Nuriza','Saltanat','Zarina']},
    'tajik': {
        'surnames': ['Rahmon','Mirzo','Saidov','Karimov','Sharipov','Nazarov','Tursunov','Khudoev'],
        'male': ['Firuz','Daler','Komron','Rustam','Farkhod','Jamshed','Bahrom','Dilshod'],
        'female': ['Madina','Nilufar','Farzona','Gulnora','Firuza','Shahnoza','Parvina','Sitora']},
    'turkmen': {
        'surnames': ['Berdimuhamedov','Niyazov','Atayev','Rejepov','Muradov','Gurbanov','Orazov','Charyyev'],
        'male': ['Berdi','Dovlet','Gurban','Merdan','Maksat','Myrat','Serdar','Vepa'],
        'female': ['Ayna','Bahar','Gozel','Jennet','Maral','Ogulgerek','Selbi','Zuleyha']},
    'afghan': {
        'surnames': ['Ahmadzai','Karzai','Ghani','Mohammadi','Noorzai','Popalzai','Durrani','Wardak'],
        'male': ['Ahmad','Mohammad','Abdul','Farid','Hamid','Karim','Noor','Rashid'],
        'female': ['Fatima','Mariam','Zahra','Laila','Nafisa','Shakila','Roya','Freshta']},

    # ── East Europe & Russia ──
    'russian': {
        'surnames': ['Ivanov','Smirnov','Kuznetsov','Popov','Vasiliev','Petrov','Sokolov','Volkov','Fedorov','Morozov'],
        'male': ['Alexander','Dmitri','Maxim','Ivan','Artem','Nikolai','Mikhail','Andrei','Pavel','Sergei'],
        'female': ['Anastasia','Maria','Daria','Anna','Sofia','Viktoria','Polina','Ekaterina','Alina','Olga']},
    'ukrainian': {
        'surnames': ['Shevchenko','Kovalenko','Bondarenko','Tkachenko','Kravchenko','Melnyk','Boyko','Lysenko'],
        'male': ['Oleksandr','Dmytro','Maksym','Andriy','Bogdan','Volodymyr','Taras','Yaroslav'],
        'female': ['Olena','Natalia','Tetiana','Oksana','Iryna','Yulia','Svitlana','Daryna']},
    'belarusian': {
        'surnames': ['Ivanov','Kazlov','Novikau','Maroz','Barysevich','Kravchanka','Shymanski','Vasilyeu'],
        'male': ['Ales','Mikita','Dzmitry','Kirill','Yahor','Uladzimir','Pavel','Andrei'],
        'female': ['Katsiaryna','Hanna','Darya','Maryia','Nastassia','Alena','Volha','Iryna']},
    'polish': {
        'surnames': ['Nowak','Kowalski','Wisniewski','Wojciechowski','Kaminski','Lewandowski','Zielinski','Szymanski'],
        'male': ['Jan','Jakub','Szymon','Filip','Kacper','Mateusz','Aleksander','Michal'],
        'female': ['Anna','Maria','Katarzyna','Agnieszka','Zofia','Maja','Zuzanna','Julia']},
    'czech': {
        'surnames': ['Novak','Svoboda','Novotny','Dvorak','Cerny','Prochazka','Kucera','Vesely'],
        'male': ['Jan','Jakub','Tomas','Adam','Filip','Matej','Vojtech','Ondrej'],
        'female': ['Tereza','Anna','Eliska','Adela','Barbora','Katerina','Natalie','Kristyna']},
    'slovak': {
        'surnames': ['Horvath','Kovac','Varga','Toth','Kocis','Balogh','Nagy','Molnar'],
        'male': ['Jakub','Adam','Samuel','Martin','Simon','Tomas','Filip','Matej'],
        'female': ['Sofia','Nina','Emma','Ela','Hana','Nela','Laura','Viktoria']},
    'hungarian': {
        'surnames': ['Nagy','Kovacs','Toth','Szabo','Horvath','Varga','Kiss','Molnar'],
        'male': ['Bence','Mate','Levente','Dominik','Adam','Milan','David','Balazs'],
        'female': ['Hanna','Anna','Luca','Emma','Zsofia','Lili','Nora','Boglarka']},
    'romanian': {
        'surnames': ['Popa','Popescu','Ionescu','Dumitrescu','Stan','Stoica','Gheorghe','Rusu'],
        'male': ['Andrei','Alexandru','David','Stefan','Gabriel','Mihai','Daniel','Cristian'],
        'female': ['Maria','Andreea','Elena','Alexandra','Ioana','Ana','Cristina','Diana']},
    'bulgarian': {
        'surnames': ['Ivanov','Georgiev','Dimitrov','Petrov','Nikolov','Hristov','Todorov','Stoyanov'],
        'male': ['Georgi','Ivan','Dimitar','Nikolai','Alexander','Martin','Boris','Todor'],
        'female': ['Maria','Ivanka','Elena','Yordanka','Penka','Daniela','Desislava','Gabriela']},
    'moldovan': {
        'surnames': ['Popescu','Rusu','Moraru','Cojocaru','Ceban','Lungu','Munteanu','Rosca'],
        'male': ['Ion','Vasile','Dumitru','Alexandru','Mihai','Andrei','Stefan','Gheorghe'],
        'female': ['Maria','Ana','Elena','Natalia','Tatiana','Olga','Irina','Valentina']},

    # ── Western Europe ──
    'english': {
        'surnames': ['Smith','Johnson','Williams','Brown','Jones','Davis','Miller','Wilson','Taylor','Anderson'],
        'male': ['James','John','Robert','Michael','William','David','Richard','Joseph','Thomas','Oliver'],
        'female': ['Mary','Patricia','Jennifer','Linda','Barbara','Susan','Jessica','Sarah','Emma','Olivia']},
    'german': {
        'surnames': ['Mueller','Schmidt','Schneider','Fischer','Weber','Meyer','Wagner','Becker','Schulz','Hoffmann'],
        'male': ['Lukas','Leon','Finn','Noah','Paul','Felix','Elias','Jonas','Ben','Maximilian'],
        'female': ['Emma','Mia','Hannah','Sofia','Lina','Emilia','Marie','Lena','Anna','Lea']},
    'french': {
        'surnames': ['Martin','Bernard','Dubois','Thomas','Robert','Richard','Petit','Durand','Leroy','Moreau'],
        'male': ['Louis','Gabriel','Raphael','Jules','Adam','Lucas','Leo','Hugo','Arthur','Nathan'],
        'female': ['Emma','Jade','Louise','Alice','Chloe','Lina','Rose','Lea','Manon','Ines']},
    'italian': {
        'surnames': ['Rossi','Russo','Ferrari','Esposito','Bianchi','Romano','Colombo','Ricci','Marino','Greco'],
        'male': ['Leonardo','Francesco','Alessandro','Lorenzo','Andrea','Matteo','Gabriele','Riccardo'],
        'female': ['Sofia','Giulia','Aurora','Alice','Ginevra','Emma','Giorgia','Greta']},
    'spanish': {
        'surnames': ['Garcia','Rodriguez','Martinez','Lopez','Gonzalez','Hernandez','Perez','Sanchez','Ramirez','Torres'],
        'male': ['Hugo','Martin','Lucas','Daniel','Pablo','Alejandro','Mateo','Adrian','Leo','Alvaro'],
        'female': ['Lucia','Sofia','Maria','Martina','Julia','Paula','Daniela','Valentina','Alba','Emma']},
    'portuguese': {
        'surnames': ['Silva','Santos','Ferreira','Pereira','Oliveira','Costa','Rodrigues','Martins','Sousa','Fernandes'],
        'male': ['Joao','Francisco','Santiago','Afonso','Rodrigo','Tomas','Miguel','Guilherme'],
        'female': ['Maria','Leonor','Matilde','Beatriz','Carolina','Mariana','Ana','Ines']},
    'dutch': {
        'surnames': ['De Jong','Jansen','De Vries','Van den Berg','Bakker','Visser','Smit','Meijer'],
        'male': ['Daan','Sem','Lucas','Levi','Finn','Luuk','Milan','Jesse'],
        'female': ['Emma','Julia','Tessa','Sophie','Saar','Lotte','Eva','Anna']},
    'belgian': {
        'surnames': ['Peeters','Janssens','Maes','Jacobs','Willems','Claes','Mertens','Goossens'],
        'male': ['Louis','Arthur','Noah','Lucas','Liam','Victor','Jules','Adam'],
        'female': ['Emma','Louise','Olivia','Alice','Charlotte','Lea','Juliette','Noor']},
    'swiss': {
        'surnames': ['Mueller','Meier','Schmid','Keller','Weber','Huber','Schneider','Meyer'],
        'male': ['Noah','Liam','Leon','Luca','Matteo','Elias','Louis','David'],
        'female': ['Mia','Emma','Elena','Lara','Laura','Lea','Anna','Lina']},
    'austrian': {
        'surnames': ['Gruber','Huber','Bauer','Wagner','Mueller','Pichler','Steiner','Moser'],
        'male': ['Paul','David','Maximilian','Felix','Lukas','Jakob','Elias','Jonas'],
        'female': ['Anna','Laura','Valentina','Marie','Lena','Sophie','Leonie','Hannah']},
    'luxembourgish': {
        'surnames': ['Muller','Weber','Schmit','Hoffmann','Wagner','Klein','Thill','Reuter'],
        'male': ['Luca','Maxime','Noah','Ben','Leo','Arthur','Louis','Tom'],
        'female': ['Emma','Marie','Lena','Anna','Mia','Lea','Sophie','Clara']},
    'irish': {
        'surnames': ['Murphy','Kelly','Byrne','Ryan','Walsh','Sullivan','O\'Brien','O\'Connor'],
        'male': ['Jack','James','Conor','Daniel','Sean','Liam','Fionn','Cillian'],
        'female': ['Emily','Sophie','Aoife','Grace','Ava','Ciara','Saoirse','Roisin']},
    'scottish': {
        'surnames': ['Smith','Brown','Wilson','Campbell','Stewart','Thomson','Robertson','Anderson'],
        'male': ['Jack','Lewis','James','Oliver','Logan','Alexander','Harris','Leo'],
        'female': ['Olivia','Emily','Isla','Sophie','Ella','Ava','Amelia','Grace']},
    'welsh': {
        'surnames': ['Jones','Williams','Davies','Thomas','Evans','Roberts','Lewis','Morgan'],
        'male': ['Oliver','Noah','Jack','Arthur','George','Leo','Theo','Oscar'],
        'female': ['Olivia','Amelia','Isla','Ava','Mia','Lily','Ivy','Freya']},
    'icelandic': {
        'surnames': ['Jonsson','Sigurdsson','Gudmundsson','Gunnarsson','Olafsson','Kristjansson','Stefansson','Magnusson'],
        'male': ['Jon','Sigurdur','Gudmundur','Gunnar','Olafur','Kristjan','Stefan','Magnus'],
        'female': ['Gudrun','Sigridur','Anna','Kristin','Margret','Helga','Johanna','Ingibjorg']},
    'danish': {
        'surnames': ['Nielsen','Jensen','Hansen','Pedersen','Andersen','Christensen','Larsen','Sorensen'],
        'male': ['William','Oscar','Noah','Lucas','Victor','Oliver','Alfred','Carl'],
        'female': ['Alma','Emma','Ida','Ella','Freja','Clara','Sofia','Olivia']},
    'norwegian': {
        'surnames': ['Hansen','Johansen','Olsen','Larsen','Andersen','Pedersen','Nilsen','Kristiansen'],
        'male': ['Jakob','Emil','Noah','Oliver','Filip','William','Lucas','Liam'],
        'female': ['Emma','Nora','Olivia','Ella','Ingrid','Maja','Sofia','Emilie']},
    'swedish': {
        'surnames': ['Andersson','Johansson','Karlsson','Nilsson','Eriksson','Larsson','Olsson','Persson'],
        'male': ['Liam','Noah','William','Hugo','Lucas','Oscar','Oliver','Adam'],
        'female': ['Alice','Maja','Elsa','Astrid','Wilma','Saga','Ebba','Olivia']},
    'finnish': {
        'surnames': ['Korhonen','Virtanen','Makinen','Nieminen','Makela','Hamalainen','Laine','Heikkinen'],
        'male': ['Leo','Elias','Eino','Vaino','Onni','Noel','Oliver','Veikka'],
        'female': ['Aino','Eevi','Emma','Sofia','Aada','Lilja','Helmi','Venla']},
    'estonian': {
        'surnames': ['Tamm','Saar','Magi','Kask','Kukk','Rebane','Ilves','Sepp'],
        'male': ['Rasmus','Oliver','Robin','Hugo','Markus','Martin','Karl','Mattias'],
        'female': ['Sofia','Maria','Mia','Hanna','Emma','Laura','Anna','Liisa']},
    'latvian': {
        'surnames': ['Berzins','Kalns','Ozols','Jansons','Ozolins','Petersons','Liepa','Krumins'],
        'male': ['Roberts','Markuss','Daniels','Arturs','Emils','Gustavs','Karlis','Ralfs'],
        'female': ['Sofija','Marta','Emilija','Alise','Anna','Eliza','Paula','Lote']},
    'lithuanian': {
        'surnames': ['Kazlauskas','Jankaitis','Petrauskas','Stankevičius','Vasiliauskas','Žukauskas'],
        'male': ['Lukas','Matas','Nojus','Dominykas','Kajus','Benas','Jokubas','Ignas'],
        'female': ['Emilija','Gabija','Kamile','Ugne','Ieva','Leja','Ema','Ausrine']},

    # ── Balkans ──
    'serbian': {
        'surnames': ['Jovanovic','Petrovic','Nikolic','Djordjevic','Stojanovic','Ilic','Markovic','Popovic'],
        'male': ['Luka','Vuk','Nikola','Stefan','Dusan','Marko','Filip','Aleksa'],
        'female': ['Milica','Ana','Mina','Sara','Teodora','Maja','Jovana','Katarina']},
    'croatian': {
        'surnames': ['Horvat','Kovacevic','Babic','Maric','Juric','Novak','Knezevic','Petrovic'],
        'male': ['Luka','Ivan','Marko','Filip','Mateo','Josip','Leon','David'],
        'female': ['Ana','Lucija','Mia','Petra','Sara','Ema','Elena','Laura']},
    'bosnian': {
        'surnames': ['Hodžić','Hasanovic','Kovacevic','Mehmedovic','Muratovic','Ibrahimovic','Bašić','Delic'],
        'male': ['Amer','Emir','Adnan','Haris','Tarik','Faris','Eldin','Armin'],
        'female': ['Amina','Emina','Lejla','Ajla','Lamija','Nejra','Amra','Adna']},
    'slovenian': {
        'surnames': ['Novak','Horvat','Krajnc','Kovac','Potocnik','Turk','Vidmar','Golob'],
        'male': ['Luka','Filip','Jakob','Nik','Mark','Jan','Zan','Tim'],
        'female': ['Eva','Ema','Zala','Ana','Lara','Nia','Maja','Sara']},
    'macedonian': {
        'surnames': ['Stojanovski','Dimitrovski','Petrovski','Ivanovski','Nikolovski','Trajkovski'],
        'male': ['Aleksandar','Marko','Nikola','Stefan','David','Filip','Luka','Darko'],
        'female': ['Marija','Ana','Maja','Emilija','Sara','Teodora','Elena','Ivana']},
    'albanian': {
        'surnames': ['Hoxha','Shehu','Leka','Basha','Kelmendi','Berisha','Duka','Gashi'],
        'male': ['Arlind','Erion','Dritan','Gentian','Besnik','Armand','Klejdi','Endrit'],
        'female': ['Elira','Teuta','Besa','Drita','Flutura','Lule','Blerta','Mimoza']},
    'greek': {
        'surnames': ['Papadopoulos','Vlahos','Angelopoulos','Nikolaidis','Papadakis','Georgiou','Konstantinou'],
        'male': ['Georgios','Dimitrios','Ioannis','Konstantinos','Nikolaos','Panagiotis','Christos','Andreas'],
        'female': ['Maria','Eleni','Aikaterini','Dimitra','Sofia','Anastasia','Georgia','Christina']},
    'turkish': {
        'surnames': ['Yilmaz','Kaya','Demir','Celik','Sahin','Ozturk','Yildiz','Ozdemir','Aydın','Arslan'],
        'male': ['Yusuf','Berat','Kerem','Eymen','Omer','Mustafa','Emir','Miraç'],
        'female': ['Zeynep','Elif','Defne','Azra','Ecrin','Asya','Eylul','Nehir']},
    'cypriot': {
        'surnames': ['Georgiou','Charalambous','Ioannou','Nicolaou','Antoniou','Christodoulou','Constantinou'],
        'male': ['Andreas','Georgios','Christos','Constantinos','Panayiotis','Michael','Stelios','Nikos'],
        'female': ['Maria','Elena','Christina','Sophia','Anna','Georgia','Eleni','Katerina']},

    # ── Middle East ──
    'arabic': {
        'surnames': ['Al-Ahmad','Al-Hassan','Al-Ali','Al-Mohammed','Al-Ibrahim','Al-Khalil','Al-Rashid'],
        'male': ['Omar','Ali','Hassan','Ahmed','Youssef','Khalid','Tariq','Zayd','Hamza','Ibrahim'],
        'female': ['Fatima','Aisha','Layla','Nour','Yasmin','Hana','Rania','Sara','Amina','Zainab']},
    'iranian': {
        'surnames': ['Ahmadi','Hosseini','Mohammadi','Rezaei','Karimi','Mousavi','Hashemi','Moradi'],
        'male': ['Ali','Mohammad','Amir','Hossein','Reza','Mehdi','Sajjad','Armin','Parsa','Dariush'],
        'female': ['Zahra','Fatemeh','Maryam','Sara','Narges','Mahsa','Nazanin','Setareh','Parisa','Shirin']},
    'iraqi': {
        'surnames': ['Al-Sadr','Al-Maliki','Al-Hashimi','Al-Janabi','Al-Dulaimi','Al-Obaidi'],
        'male': ['Ali','Hussein','Ahmad','Mohammed','Omar','Mustafa','Kareem','Haider'],
        'female': ['Noor','Zahra','Fatima','Sara','Mariam','Huda','Rana','Dina']},
    'syrian': {
        'surnames': ['Al-Assad','Ibrahim','Khalil','Haddad','Nasri','Saleh','Yousef','Darwish'],
        'male': ['Ahmad','Youssef','Omar','Khaled','Sami','Fadi','Nabil','Rami'],
        'female': ['Lina','Rana','Dina','Rima','Maya','Ghada','Hala','Noura']},
    'jordanian': {
        'surnames': ['Al-Abdullah','Al-Hussein','Haddadin','Tarawneh','Batayneh','Obeidat','Rawashdeh'],
        'male': ['Ahmad','Mohammad','Omar','Zaid','Yazeed','Hamza','Anas','Youssef'],
        'female': ['Lina','Rana','Dina','Noor','Haya','Reem','Dana','Rawan']},
    'lebanese': {
        'surnames': ['Khoury','Haddad','Nassar','Rizk','Saade','Daher','Najm','Makhlouf'],
        'male': ['Georges','Elie','Pierre','Rami','Charbel','Sami','Fadi','Marc'],
        'female': ['Nour','Maya','Lara','Aya','Lea','Sara','Nadine','Mia']},
    'israeli': {
        'surnames': ['Cohen','Levi','Mizrahi','Peretz','Biton','Dahan','Azoulay','Friedman'],
        'male': ['Yosef','David','Moshe','Noam','Itai','Uri','Ariel','Eitan'],
        'female': ['Noa','Tamar','Yael','Shira','Maya','Adel','Avigail','Lia']},
    'saudi': {
        'surnames': ['Al-Saud','Al-Rashid','Al-Otaibi','Al-Ghamdi','Al-Zahrani','Al-Shehri','Al-Qahtani'],
        'male': ['Mohammed','Abdulaziz','Faisal','Sultan','Turki','Khalid','Nawaf','Bandar'],
        'female': ['Noura','Haya','Sara','Lama','Reem','Dalal','Abeer','Maha']},
    'emirati': {
        'surnames': ['Al-Nahyan','Al-Maktoum','Al-Nuaimi','Al-Mualla','Al-Sharqi','Al-Qassimi'],
        'male': ['Mohammed','Ahmed','Rashid','Sultan','Hamdan','Saeed','Khalifa','Mansour'],
        'female': ['Shamma','Latifa','Maitha','Alia','Hessa','Mouza','Fatima','Salama']},
    'kuwaiti': {
        'surnames': ['Al-Sabah','Al-Mutawa','Al-Shatti','Al-Kandari','Al-Enezi','Al-Rashidi'],
        'male': ['Bader','Fahad','Hamad','Yousef','Khalid','Faisal','Abdulaziz','Meshal'],
        'female': ['Dalal','Hessa','Noura','Reem','Sara','Fatima','Maryam','Sheikha']},
    'qatari': {
        'surnames': ['Al-Thani','Al-Attiyah','Al-Kuwari','Al-Marri','Al-Sulaiti','Al-Muhannadi'],
        'male': ['Hamad','Khalifa','Tamim','Jassim','Nasser','Mohammed','Ahmed','Abdulaziz'],
        'female': ['Moza','Noora','Hind','Shaikha','Asma','Reem','Sara','Aisha']},
    'bahraini': {
        'surnames': ['Al-Khalifa','Al-Dosari','Al-Mannai','Al-Zayani','Fakhroo','Al-Maawda'],
        'male': ['Ahmed','Mohammed','Ali','Hassan','Youssef','Ibrahim','Salman','Khalid'],
        'female': ['Zainab','Fatima','Mariam','Noor','Hala','Eman','Dana','Maryam']},
    'omani': {
        'surnames': ['Al-Said','Al-Busaidi','Al-Harthi','Al-Balushi','Al-Habsi','Al-Rawahi'],
        'male': ['Said','Qaboos','Haitham','Mohammed','Ahmed','Abdullah','Salim','Hamad'],
        'female': ['Asma','Fatima','Mariam','Khadija','Aisha','Salma','Ruqayya','Zahra']},
    'yemeni': {
        'surnames': ['Al-Ahmar','Al-Houthi','Saleh','Al-Zindani','Al-Shami','Al-Sana'],
        'male': ['Abdullah','Mohammed','Ali','Ahmed','Omar','Nasser','Saleh','Hamid'],
        'female': ['Fatima','Amina','Khadija','Zahra','Salma','Noor','Huda','Samira']},

    # ── Africa ──
    'egyptian': {
        'surnames': ['Mohamed','Ahmed','Hassan','Ibrahim','Ali','Mahmoud','Mostafa','Abdel'],
        'male': ['Mohamed','Ahmed','Mahmoud','Mostafa','Omar','Youssef','Ali','Amr'],
        'female': ['Fatma','Mariam','Nour','Hana','Salma','Yasmin','Sara','Dina']},
    'moroccan': {
        'surnames': ['Benali','Idrissi','El-Amrani','Benhaddou','Tazi','Fassi','Kettani','Alaoui'],
        'male': ['Youssef','Adam','Amine','Hamza','Rayan','Ilyas','Bilal','Mehdi'],
        'female': ['Fatima-Zahra','Aya','Maryam','Douaa','Salma','Hajar','Nour','Imane']},
    'algerian': {
        'surnames': ['Benkhedda','Bouteflika','Benhamouda','Mekhloufi','Belhadj','Mahrez','Zidane'],
        'male': ['Mohamed','Amine','Rayan','Adem','Younes','Islem','Ayoub','Bilal'],
        'female': ['Meriem','Aya','Amira','Ines','Lina','Nour','Rania','Sara']},
    'tunisian': {
        'surnames': ['Ben Ali','Trabelsi','Bouazizi','Jebali','Essid','Marzouki','Ghannouchi'],
        'male': ['Mohamed','Ahmed','Youssef','Adam','Aziz','Hamza','Amine','Bilal'],
        'female': ['Mariam','Aya','Eya','Ranim','Fatma','Ines','Amira','Chaima']},
    'libyan': {
        'surnames': ['Gaddafi','Haftar','Sarraj','Magariaf','Jibril','El-Sharif','Dbeibah'],
        'male': ['Mohammed','Ahmed','Ali','Omar','Muammar','Saif','Khalifa','Fathi'],
        'female': ['Fatima','Aisha','Khadija','Mariam','Salma','Nadia','Huda','Samira']},
    'nigerian': {
        'surnames': ['Okafor','Adeyemi','Ibrahim','Musa','Okonkwo','Adebayo','Abubakar','Oluwaseun'],
        'male': ['Chukwuemeka','Olumide','Abdullahi','Chibuike','Adewale','Uche','Tunde','Emeka'],
        'female': ['Chidinma','Adebimpe','Amina','Ngozi','Oluwatimileyin','Fatima','Aisha','Ifeoma']},
    'south_african': {
        'surnames': ['Van der Merwe','Nkosi','Dlamini','Zulu','Botha','Pillay','Mokoena','Smith'],
        'male': ['Sipho','Thabo','Pieter','Johan','Liam','Bongani','Mandla','Jason'],
        'female': ['Nomsa','Thandiwe','Lerato','Anele','Minenhle','Zanele','Palesa','Liesl']},
    'kenyan': {
        'surnames': ['Kipchoge','Wanjiku','Odhiambo','Muthoni','Kamau','Otieno','Njeri','Achieng'],
        'male': ['Brian','Kevin','Dennis','Peter','John','James','Samuel','David'],
        'female': ['Faith','Grace','Mercy','Joy','Hope','Esther','Mary','Agnes']},
    'ghanaian': {
        'surnames': ['Mensah','Asante','Boateng','Owusu','Adjei','Amoah','Ofori','Danquah'],
        'male': ['Kwame','Kofi','Kwesi','Yaw','Kojo','Kwaku','Nana','Ato'],
        'female': ['Ama','Akua','Abena','Yaa','Adjoa','Afia','Akosua','Efua']},
    'ethiopian': {
        'surnames': ['Haile','Getachew','Tadesse','Bekele','Gebrselassie','Mekonnen','Tesfaye','Abebe'],
        'male': ['Abebe','Dawit','Yohannes','Solomon','Mekonnen','Girma','Teshome','Hailu'],
        'female': ['Tigist','Meron','Bethlehem','Hiwot','Sara','Yeshi','Selamawit','Meseret']},
    'tanzanian': {
        'surnames': ['Nyerere','Mkapa','Mwinyi','Magufuli','Massawe','Mwakasege','Kimaro'],
        'male': ['Baraka','Juma','Hamisi','Said','Bakari','Rashid','Omari','Hassan'],
        'female': ['Neema','Amina','Zawadi','Rehema','Furaha','Hadija','Mwanaisha','Zainab']},
    'ugandan': {
        'surnames': ['Museveni','Obote','Ssempa','Kiggundu','Namuganza','Byaruhanga','Tumusiime'],
        'male': ['David','Joseph','Peter','Samuel','Moses','Isaac','Andrew','Simon'],
        'female': ['Grace','Sarah','Mary','Ruth','Esther','Deborah','Miriam','Rebecca']},
    'congolese': {
        'surnames': ['Kabila','Tshisekedi','Mobutu','Lumumba','Katumbi','Bemba','Moise','Ngandu'],
        'male': ['Joseph','Patrice','Jean','Pierre','Felix','Martin','Claude','Emmanuel'],
        'female': ['Marie','Josephine','Bernadette','Therese','Esperance','Jeanne','Anais','Nadine']},
    'senegalese': {
        'surnames': ['Diop','Ndiaye','Fall','Seck','Gueye','Ba','Diallo','Sy'],
        'male': ['Mamadou','Ousmane','Ibrahima','Cheikh','Abdoulaye','Moussa','Amadou','Pape'],
        'female': ['Fatou','Aissatou','Aminata','Mariama','Ndèye','Khady','Adama','Binta']},
    'ivorian': {
        'surnames': ['Ouattara','Gbagbo','Toure','Konan','Bédié','Kone','Coulibaly','Diallo'],
        'male': ['Moussa','Ibrahim','Seydou','Amadou','Youssouf','Drissa','Bakary','Alassane'],
        'female': ['Aminata','Mariam','Fatoumata','Djénéba','Kadiatou','Awa','Rokia','Assita']},
    'cameroonian': {
        'surnames': ['Biya','Fru','Ndi','Eto\'o','Mbappé','Mboma','Song','Nkoulou'],
        'male': ['Samuel','Pierre','Jean','Paul','Emmanuel','Patrick','Fabrice','Stephane'],
        'female': ['Marie','Nadine','Sandrine','Carine','Viviane','Pauline','Florence','Estelle']},
    'rwandan': {
        'surnames': ['Kagame','Habyarimana','Nzabonimana','Uwimana','Mugisha','Ndayisaba','Habimana'],
        'male': ['Jean-Pierre','Emmanuel','Patrick','Eric','Innocent','Celestin','Claude','Didier'],
        'female': ['Diane','Claudine','Yvonne','Immaculee','Esperance','Jeannette','Goretti','Assumpta']},

    # ── Americas ──
    'american': {
        'surnames': ['Smith','Johnson','Williams','Brown','Jones','Garcia','Miller','Davis','Rodriguez','Martinez'],
        'male': ['Liam','Noah','Oliver','James','Elijah','William','Henry','Lucas','Benjamin','Theodore'],
        'female': ['Olivia','Emma','Charlotte','Amelia','Sophia','Mia','Isabella','Ava','Evelyn','Luna']},
    'canadian': {
        'surnames': ['Smith','Brown','Tremblay','Martin','Roy','Wilson','Gagnon','Taylor','Macdonald','Campbell'],
        'male': ['Liam','Noah','Oliver','Jack','Benjamin','William','Lucas','James','Ethan','Owen'],
        'female': ['Olivia','Emma','Charlotte','Amelia','Sophia','Isla','Ava','Ella','Mia','Chloe']},
    'mexican': {
        'surnames': ['Hernandez','Garcia','Martinez','Lopez','Gonzalez','Rodriguez','Perez','Sanchez'],
        'male': ['Santiago','Mateo','Sebastian','Leonardo','Daniel','Matias','Nicolas','Samuel'],
        'female': ['Valentina','Sofia','Isabella','Camila','Victoria','Regina','Natalia','Ximena']},
    'brazilian': {
        'surnames': ['Silva','Santos','Oliveira','Souza','Rodrigues','Ferreira','Alves','Pereira'],
        'male': ['Miguel','Arthur','Gael','Heitor','Theo','Davi','Gabriel','Bernardo'],
        'female': ['Helena','Alice','Laura','Maria','Valentina','Heloisa','Sophia','Julia']},
    'argentine': {
        'surnames': ['Gonzalez','Rodriguez','Gomez','Fernandez','Lopez','Martinez','Garcia','Diaz'],
        'male': ['Mateo','Santiago','Thiago','Benjamin','Bautista','Valentino','Santino','Lautaro'],
        'female': ['Sofia','Isabella','Valentina','Emma','Mia','Catalina','Delfina','Martina']},
    'colombian': {
        'surnames': ['Gomez','Rodriguez','Garcia','Martinez','Lopez','Gonzalez','Hernandez','Diaz'],
        'male': ['Samuel','Santiago','Matias','Sebastian','Alejandro','Daniel','Nicolas','Juan'],
        'female': ['Sofia','Isabella','Valentina','Salome','Mariana','Gabriela','Sara','Daniela']},
    'chilean': {
        'surnames': ['Gonzalez','Muñoz','Rojas','Diaz','Perez','Soto','Contreras','Silva'],
        'male': ['Agustin','Matias','Benjamin','Vicente','Martin','Tomas','Joaquin','Alonso'],
        'female': ['Agustina','Sofia','Martina','Isidora','Florencia','Emilia','Maite','Amanda']},
    'peruvian': {
        'surnames': ['Garcia','Rodriguez','Martinez','Flores','Lopez','Gonzalez','Chavez','Quispe'],
        'male': ['Santiago','Mateo','Sebastian','Lucas','Benjamin','Nicolas','Thiago','Adrian'],
        'female': ['Valentina','Mia','Luciana','Camila','Isabella','Ariana','Victoria','Renata']},
    'venezuelan': {
        'surnames': ['Rodriguez','Gonzalez','Hernandez','Garcia','Martinez','Lopez','Diaz','Perez'],
        'male': ['Santiago','Sebastian','Samuel','Matias','Daniel','David','Gabriel','Adrian'],
        'female': ['Valentina','Camila','Isabella','Sofia','Victoria','Daniela','Gabriela','Andrea']},
    'cuban': {
        'surnames': ['Rodriguez','Gonzalez','Hernandez','Garcia','Martinez','Lopez','Perez','Diaz'],
        'male': ['Alejandro','Daniel','Carlos','Luis','Jorge','Miguel','Rafael','Pedro'],
        'female': ['Maria','Yamilet','Dayami','Lisandra','Yanet','Yadira','Marisol','Alina']},
    'jamaican': {
        'surnames': ['Brown','Williams','Campbell','Stewart','James','Anderson','Thomas','Morgan'],
        'male': ['Michael','David','Andre','Omar','Damion','Dexter','Wayne','Usain'],
        'female': ['Shelly-Ann','Elaine','Asafa','Keisha','Tanesha','Shericka','Natasha','Monique']},
    'haitian': {
        'surnames': ['Jean','Pierre','Joseph','Louis','Baptiste','Charles','Francois','Edouard'],
        'male': ['Jean','Pierre','Maxime','Frantz','Rene','Claude','Philippe','Gerald'],
        'female': ['Marie','Rose','Nadine','Guerda','Martine','Magalie','Fabienne','Yanick']},

    # ── Oceania ──
    'australian': {
        'surnames': ['Smith','Jones','Williams','Brown','Wilson','Taylor','Johnson','White','Martin','Anderson'],
        'male': ['Oliver','Noah','Jack','William','Leo','Lucas','Henry','Charlie'],
        'female': ['Charlotte','Olivia','Amelia','Isla','Mia','Ava','Grace','Chloe']},
    'new_zealander': {
        'surnames': ['Smith','Williams','Brown','Wilson','Taylor','Anderson','Thomas','Harris'],
        'male': ['Oliver','Jack','Noah','Leo','James','Lucas','George','Liam'],
        'female': ['Isla','Charlotte','Amelia','Olivia','Ava','Mia','Lily','Harper']},
    'fijian': {
        'surnames': ['Kumar','Singh','Prasad','Nand','Chand','Ratu','Tuisawau','Nailatikau'],
        'male': ['Viliame','Josaia','Apisai','Semi','Leone','Manasa','Josefa','Ilikena'],
        'female': ['Mere','Adi','Litia','Vasiti','Kelera','Salote','Merewalesi','Emi']},
    'samoan': {
        'surnames': ['Tuilagi','Savea','Polamalu','Lomu','Tuiasosopo','Maiava','Ioane','Nanai'],
        'male': ['Manu','Tana','Sione','Latu','Peni','Tavita','Malietoa','Aiga'],
        'female': ['Sina','Leilani','Moana','Teuila','Nafanua','Taema','Losa','Malia']},
    'tongan': {
        'surnames': ['Tupou','Mafi','Taufa','Vea','Aho','Latu','Kaufusi','Tonga'],
        'male': ['Sione','Tevita','Viliami','Samuela','Tupou','Peni','Malakai','Latu'],
        'female': ['Ana','Salote','Mele','Sela','Lupe','Vika','Ilaisaane','Fifita']},
    'papua_new_guinean': {
        'surnames': ['Kumul','Morea','Bai','Kuman','Tago','Mane','Oa','Ravu'],
        'male': ['John','Peter','James','Michael','David','Paul','Joseph','Thomas'],
        'female': ['Mary','Rose','Elizabeth','Margaret','Grace','Ruth','Sarah','Agnes']},

    # ── Caribbean / Central America ──
    'dominican': {
        'surnames': ['Rodriguez','Martinez','Garcia','Hernandez','Perez','Sanchez','Ramirez','De la Cruz'],
        'male': ['Juan','Carlos','Miguel','Rafael','Angel','Pedro','Francisco','Luis'],
        'female': ['Maria','Rosa','Ana','Carmen','Luz','Juana','Altagracia','Mercedes']},
    'puerto_rican': {
        'surnames': ['Rivera','Rodriguez','Santiago','Torres','Diaz','Morales','Ortiz','Cruz'],
        'male': ['Luis','Juan','Carlos','Angel','Jose','Javier','Rafael','Miguel'],
        'female': ['Maria','Ana','Carmen','Luz','Rosa','Isabel','Marta','Laura']},
    'costa_rican': {
        'surnames': ['Rodriguez','Gonzalez','Hernandez','Garcia','Ramirez','Mora','Jimenez','Vargas'],
        'male': ['Jose','Carlos','Juan','Daniel','David','Andres','Diego','Sebastian'],
        'female': ['Maria','Ana','Laura','Daniela','Andrea','Gabriela','Valeria','Natalia']},
    'guatemalan': {
        'surnames': ['Lopez','Garcia','Martinez','Hernandez','Gonzalez','Perez','Morales','Rodriguez'],
        'male': ['Jose','Carlos','Juan','Miguel','Pedro','Francisco','Diego','Luis'],
        'female': ['Maria','Rosa','Ana','Carmen','Juana','Marta','Lucia','Sandra']},
    'honduran': {
        'surnames': ['Lopez','Martinez','Garcia','Hernandez','Rodriguez','Gonzalez','Ramirez','Cruz'],
        'male': ['Jose','Juan','Carlos','Luis','Daniel','David','Pedro','Miguel'],
        'female': ['Maria','Ana','Rosa','Sandra','Karla','Wendy','Lidia','Xiomara']},
    'salvadoran': {
        'surnames': ['Martinez','Hernandez','Lopez','Gonzalez','Garcia','Rodriguez','Ramirez','Rivera'],
        'male': ['Jose','Carlos','Juan','Luis','Daniel','David','Fernando','Oscar'],
        'female': ['Maria','Ana','Rosa','Karla','Sandra','Claudia','Patricia','Carmen']},
    'nicaraguan': {
        'surnames': ['Lopez','Martinez','Garcia','Gonzalez','Hernandez','Rodriguez','Sanchez','Ramirez'],
        'male': ['Jose','Carlos','Juan','Luis','Daniel','Francisco','Pedro','Miguel'],
        'female': ['Maria','Ana','Rosa','Martha','Carmen','Juana','Lucia','Gloria']},
    'panamanian': {
        'surnames': ['Gonzalez','Rodriguez','Martinez','Garcia','Lopez','Hernandez','Sanchez','Torres'],
        'male': ['Jose','Carlos','Luis','Juan','Omar','Ricardo','Roberto','Eduardo'],
        'female': ['Maria','Ana','Carmen','Rosa','Marta','Gloria','Luz','Isabel']},

    # ── Additional ──
    'georgian': {
        'surnames': ['Beridze','Kapanadze','Gelashvili','Maisuradze','Giorgadze','Lomidze'],
        'male': ['Giorgi','Daviti','Luka','Nikoloz','Alexandre','Tornike','Saba','Irakli'],
        'female': ['Nino','Mariam','Ana','Tamari','Salome','Elene','Natia','Ekaterine']},
    'armenian': {
        'surnames': ['Sargsyan','Harutyunyan','Grigoryan','Hovhannisyan','Mkrtchyan','Petrosyan'],
        'male': ['Hayk','Aram','Narek','Levon','Armen','Davit','Tigran','Sargis'],
        'female': ['Anna','Nane','Ani','Mariam','Anahit','Lusine','Gayane','Armine']},
    'azerbaijani': {
        'surnames': ['Aliyev','Mammadov','Hasanov','Huseynov','Guliyev','Babayev','Rajabov','Ismailov'],
        'male': ['Elvin','Tural','Murad','Orkhan','Rasul','Kamran','Emil','Farid'],
        'female': ['Aysel','Nigar','Gunel','Leyla','Fidan','Narmin','Sabina','Tunzala']},
    'maltese': {
        'surnames': ['Borg','Camilleri','Vella','Farrugia','Zammit','Micallef','Grech','Galea'],
        'male': ['Luca','Matteo','Jake','Miguel','Gabriel','Jean','Luke','Mark'],
        'female': ['Emma','Mia','Martina','Amy','Thea','Julia','Leah','Nicole']},
    'andorran': {
        'surnames': ['Lopez','Garcia','Martinez','Fernandez','Rodriguez','Torres','Sanchez','Vidal'],
        'male': ['Marc','Pol','Arnau','Jan','Eric','Alex','Biel','Nil'],
        'female': ['Laia','Julia','Martina','Carla','Aina','Lucia','Nuria','Sara']},
    'monegasque': {
        'surnames': ['Grimaldi','Leclerc','Bianchi','Rossi','Gastaud','Pastor','Rey','Aureglia'],
        'male': ['Louis','Raphael','Jules','Lucas','Arthur','Adam','Hugo','Gabriel'],
        'female': ['Emma','Lea','Camille','Chloe','Manon','Ines','Jade','Louise']},
    'liechtensteiner': {
        'surnames': ['Frick','Batliner','Buechel','Hasler','Marxer','Ospelt','Walser','Wille'],
        'male': ['Noah','Liam','Leon','Lukas','David','Felix','Julian','Tim'],
        'female': ['Mia','Emma','Lena','Anna','Lea','Lara','Sophie','Julia']},
    'san_marinese': {
        'surnames': ['Mularoni','Valentini','Celli','Gasperoni','Guidi','Zafferani','Ciavatta','Galassi'],
        'male': ['Marco','Luca','Andrea','Matteo','Alessandro','Francesco','Davide','Simone'],
        'female': ['Giulia','Sara','Chiara','Alice','Elena','Anna','Sofia','Martina']},
}
